# Generated by Django 3.2.1 on 2021-06-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0003_auto_20210509_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
