# Generated by Django 3.2.2 on 2021-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0003_auto_20210509_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user3.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
