# Generated by Django 3.2.1 on 2021-06-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0006_auto_20210610_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistemp',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optifolio.customer'),
        ),
    ]
