# Generated by Django 3.2.1 on 2021-06-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0007_alter_vistemp_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisTemp',
            new_name='VisData',
        ),
    ]
