# Generated by Django 3.2.2 on 2021-06-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0008_rename_vistemp_visdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='shares_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999),
        ),
    ]
