# Generated by Django 3.2.1 on 2021-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0009_alter_visdata_shares_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visdata',
            name='id',
        ),
        migrations.AddField(
            model_name='visdata',
            name='visdata_id',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
