# Generated by Django 3.2.1 on 2021-06-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0010_auto_20210614_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='visdata_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
