# Generated by Django 3.2.1 on 2021-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0011_alter_visdata_visdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
