# Generated by Django 3.2.1 on 2021-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0012_alter_visdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visdata',
            name='hour',
            field=models.TimeField(null=True),
        ),
    ]
