# Generated by Django 3.2.1 on 2021-06-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0015_auto_20210614_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
