# Generated by Django 3.2.1 on 2021-06-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0016_alter_visdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='visdata_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
