# Generated by Django 3.2.1 on 2021-06-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0017_alter_visdata_visdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='visdata_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
