# Generated by Django 3.2.1 on 2021-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0022_alter_visdata_visdata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visdata',
            name='visdata_id',
        ),
        migrations.AddField(
            model_name='visdata',
            name='id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
