# Generated by Django 3.2.1 on 2021-06-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0023_auto_20210617_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visdata',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='visdata',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
