# Generated by Django 3.2.1 on 2021-06-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0024_auto_20210617_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='visdata',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optifolio.customer'),
        ),
    ]
