# Generated by Django 3.2.1 on 2021-06-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0026_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
