# Generated by Django 3.2.1 on 2021-06-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0028_auto_20210618_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='visdata_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
